It lang updated
Blumlaut/EasyAdmin pull request #225
Opened 2021-07-16 20:08 UTC by ITKewai

2021-07-16 20:15 UTC, Blumlaut requested changes

2021-07-16 20:15 UTC, Blumlaut commented on language/it.json
> +    "banlistshowtypeguide": "Cambia tra Licenza e Ragioni per il ban Nel menu 'Rimuovi Ban per il giocatore'.\nRichiede una riapertura del menu.",
Why do some of these specifically mention a license?

2021-07-16 20:15 UTC, Blumlaut commented on language/it.json
> +    "chatsuggestionunban": "bandisci una licenza",
same with this one, whats wrong with it?

2021-07-16 20:15 UTC, Blumlaut commented on language/it.json
> +    "admincleanedup": "**%s** Ha cancellato tutti  **%s** in their area."
this translation is incomplete

2021-07-16 23:51 UTC, ITKewai commented on language/it.json
> +    "chatsuggestionunban": "bandisci una licenza",
Actually license sound better in Italian than indentifier, but the meaning is the same

2021-07-17 03:13 UTC, merged

2021-07-17 03:13 UTC, Blumlaut commented
Thanks!