DE updated
Blumlaut/EasyAdmin pull request #243
Opened 2021-09-10 15:43 UTC by zRxnx

German language updated

2021-09-10 15:46 UTC, Blumlaut commented on language/de.json
> +    "cleaningcar": "Lösche Fahrzeuge %s",
these 3 are wrong, it should be individual "Fahrzeug", "NPC" and "Objekt", because the "%s" is their respective id.

2021-09-10 15:50 UTC, zRxnx commented on language/de.json
> +    "cleaningcar": "Lösche Fahrzeuge %s",
hö?
I only changed the Name

2021-09-11 14:39 UTC, Blumlaut requested changes

2021-09-11 14:39 UTC, Blumlaut commented on language/de.json
> +    "cleaningcar": "Lösche Fahrzeuge %s",
yes, but cleaningcar, cleaningped and cleaningprop should be singular.

2021-09-11 14:58 UTC, zRxnx commented
![image](https://user-images.githubusercontent.com/74078713/132952059-b52ff6c5-50d4-44fb-81a8-461b6211de8f.png)

Fixed to singular

2021-09-11 14:58 UTC, zRxnx commented
oh wait sorry xD

2021-09-11 15:02 UTC, zRxnx commented
Should be fixed

2021-09-11 15:02 UTC, merged