feat: custom ban deferral cards with images/customisation supported
Blumlaut/EasyAdmin pull request #821
Opened 2024-01-29 20:31 UTC by Gravxd

### NEW Ban Deferral Cards

This update brings more customisation, improved UI/branding for server owners as well as just an overall nice addition for EasyAdmin's branding.

Before:
![FiveM_b2699_GTAProcess_C5RjUjyJ2p](https://github.com/Blumlaut/EasyAdmin/assets/75702884/95cd51ee-7a30-4fa2-97f8-2405edca4214)

After:
![FiveM_b2699_GTAProcess_zau36aBGjT](https://github.com/Blumlaut/EasyAdmin/assets/75702884/3f861433-5f40-43b6-808d-1cc44e546b60)

This change also solves or at least contributes some functionality to an original idea/"to-do" item from #419 

**New Convars**
On the documentation for installation, we have sections such as Administration Configuration & Bot Configuration, I would suggest a new section for Ban Message Configuration or something similar - just a food for thought for ease of use.

`set ea_banMessageTitleColour "#ff0000"`
This allows you to change the server name title colour, **defaults to "#354557" (easyadmin colour)**

`ea_banMessageServerName "EasyAdmin Roleplay"`
Pretty self explanatory, you can add your server name here as an owner to show at the top. **Defaults to "EasyAdmin"**

`ea_banMessageShowStaff "true/false"`
Whether or not to show a banned player who they are banned by - simply added because some servers may not want to open that staff member up to harassment or whatever it may be - again, another customisation option for server owners. **Defaults to true.**

`ea_banMessageFooter "You can appeal this ban by visiting example.com"`
Defaults to "You can appeal this by ban by visiting our discord." - server owners can change this to their forums, website, discord whatever they want, as it's HTML markdown, it's also clickable which gives nice ease of access straight to a ban appeal form. (direct reference to #419)

`ea_banMessageSubHeader "You Have Been Expelled From This City"`
Defaults to "You have been banned from this server." - Some servers may want this message to fit their branding etc, something to make it easier as people that want to change these messages will try to hardcode change which makes updating more complicated and annoying.

With this change, normally the ban reason would be `test ( Nickname: ~u~Player ), Banned by: Grav` however i used a simple function to remove the suffix (end of string) so that we can display the staff member in a separate row to clean it up (with the added option to hide staff names) - this change is only on this deferral card and does not change any other logic in the easyadmin ban system.

Thank you for reading - hopefully this can be another good addition and improvement to this resource. :)

2024-01-29 20:41 UTC, Blumlaut requested changes
looks great! some code changes i'd like to see though, currently it would break on non-english locales which is kind of a big deal

2024-01-29 20:41 UTC, Blumlaut commented on server/admin_server.lua
> +							local banMessageServerName = GetConvar("ea_banMessageServerName", "EasyAdmin")
would it be worth considering setting this to `sv_projectName` by default? i feel like not many people will actually _want_ to have EasyAdmin be the default, since the ProjectName convar is fairly strict in terms of formatting which (hopefully) not many servers will ignore, i reckon that would be a better replacement for it.

2024-01-29 20:41 UTC, Blumlaut commented on server/admin_server.lua
> +                            '</code><br><br>' .. banMessageFooter .. ' <span style="font-style: italic;"></span></p><img src="https://i.imgur.com/vRFuxUN.png" style="position: absolute;right: 15px;bo
static easyadmin image url (hosted by a third party?), nasty! 

What about making this a convar? i wonder if we can actually just plop an svg object in here by default as well..

2024-01-29 20:41 UTC, Blumlaut commented on server/admin_server.lua
> +							local banMessageReason = getStringUntilSuffix(blacklist[bi].reason, ", Banned by:")
`reasonadd` is not guaranteed to be in English.

2024-01-29 21:40 UTC, Gravxd commented on server/admin_server.lua
> +							local banMessageServerName = GetConvar("ea_banMessageServerName", "EasyAdmin")
Honestly not a bad idea but my initial concern was the characters some servers have, but after re-thinking, we can definitely do this.

2024-01-29 21:43 UTC, Gravxd commented on server/admin_server.lua
> +                            '</code><br><br>' .. banMessageFooter .. ' <span style="font-style: italic;"></span></p><img src="https://i.imgur.com/vRFuxUN.png" style="position: absolute;right: 15px;bo
Was kinda thrown on there as a proof of concept, the reason i didn't do a convar is to keep easyadmin's branding as a sort of "moderation badge" but if you feel allowing server owners to replace it with their own logo/branding is a better option, we can put a convar in for this.

2024-01-29 21:45 UTC, Gravxd commented on server/admin_server.lua
> +							local banMessageReason = getStringUntilSuffix(blacklist[bi].reason, ", Banned by:")
Yepp.. fuck. Didn't think about the translation support EA has. Do you have any ideas to how we can achieve the desired outcome? I think putting the "banned by" inside the reason should honestly be removed in favour of the (already stored) banner property showing the staff member allowing us to parse and format these properties more easily. 

Obviously the concern is, if we remove the "banned by" in the reason, this will only reflect in new bans rather than old bans which a lot of people updating will do.

2024-01-29 22:05 UTC, Blumlaut commented on server/admin_server.lua
> +                            '</code><br><br>' .. banMessageFooter .. ' <span style="font-style: italic;"></span></p><img src="https://i.imgur.com/vRFuxUN.png" style="position: absolute;right: 15px;bo
> but if you feel allowing server owners to replace it with their own logo/branding is a better option, we can put a convar in for this.

it's more a matter of "people _will_ want to change this, how can we guarantee they can do the least harm?", a convar with a sane locally-provided default would be ideal

2024-01-29 22:15 UTC, Blumlaut commented on server/admin_server.lua
> +							local banMessageReason = getStringUntilSuffix(blacklist[bi].reason, ", Banned by:")
as a quick-fix you could use a regex like `.*\),.*: (.*)` to extract the banner, but yeah ideally it'd not be part of the reason in the first place, updating the existing banlist would indeed be a bit problematic..

2024-01-29 22:16 UTC, Gravxd commented on server/admin_server.lua
> +                            '</code><br><br>' .. banMessageFooter .. ' <span style="font-style: italic;"></span></p><img src="https://i.imgur.com/vRFuxUN.png" style="position: absolute;right: 15px;bo
Ya you're right lol, less workarounds and less fuck ups of people editing source code - will update

2024-01-29 22:16 UTC, Blumlaut requested changes

2024-01-29 22:16 UTC, Blumlaut commented on server/admin_server.lua
> +							local banMessageServerName = GetConvar("sv_projectName", "EasyAdmin")
`local banMessageServerName = GetConvar("ea_banMessageServerName", GetConvar("sv_projectName", "EasyAdmin")`

2024-01-29 22:34 UTC, Gravxd reviewed
Using a third party url isn't really much of a chance, most server owners will (or should ) use the new convars to form better server branding - larger applications such as txadmin (bundled with fxserver) pull user-display images through FIveM's deferral system in IMGUR//external PNG host formats as i'm not actually sure you can reference a local SVG/PNG file. - if you can, welcome to change obviously.

2024-01-29 22:35 UTC, Gravxd commented
Convar added in above commit:
`ea_banMessageWatermark "logo-url-here"` - defaults to an easyadmin banner.

2024-01-30 00:16 UTC, Gravxd commented
The changes above should solve the code breaking aspect as it will now with each language - i honestly spent a lot of time looking for a better way to achieve the desired result but ended up settling on this so if there's a better way any suggestions are welcome.

2024-01-30 10:17 UTC, Blumlaut commented on server/admin_server.lua
> +							local banMessageWatermark = GetConvar("ea_banMessageWatermark", "https://i.imgur.com/vRFuxUN.png")
can you quickly replace this with imgur link with 
```
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAACACAYAAAB9V9ELAAAACXBIWXMAAC4jAAAuIwF4pT92AAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUIIFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMFVEsDIoK2AfkIaKOg6OIisr74Xuja9a89+bN/rXXPues852zzwfACAyWSDNRNYAMqUIeEeCDx8TG4eQuQIEKJHAAEAizZCFz/SMBAPh+PDwrIsAHvgABeNMLCADATZvAMByH/w/qQplcAYCEAcB0kThLCIAUAEB6jkKmAEBGAYCdmCZTAKAEAGDLY2LjAFAtAGAnf+bTAICd+Jl7AQBblCEVAaCRACATZYhEAGg7AKzPVopFAFgwABRmS8Q5ANgtADBJV2ZIALC3AMDOEAuyAAgMADBRiIUpAAR7AGDIIyN4AISZABRG8lc88SuuEOcqAAB4mbI8uSQ5RYFbCC1xB1dXLh4ozkkXKxQ2YQJhmkAuwnmZGTKBNA/g88wAAKCRFRHgg/P9eM4Ors7ONo62Dl8t6r8G/yJiYuP+5c+rcEAAAOF0ftH+LC+zGoA7BoBt/qIl7gRoXgugdfeLZrIPQLUAoOnaV/Nw+H48PEWhkLnZ2eXk5NhKxEJbYcpXff5nwl/AV/1s+X48/Pf14L7iJIEyXYFHBPjgwsz0TKUcz5IJhGLc5o9H/LcL//wd0yLESWK5WCoU41EScY5EmozzMqUiiUKSKcUl0v9k4t8s+wM+3zUAsGo+AXuRLahdYwP2SycQWHTA4vcAAPK7b8HUKAgDgGiD4c93/+8//UegJQCAZkmScQAAXkQkLlTKsz/HCAAARKCBKrBBG/TBGCzABhzBBdzBC/xgNoRCJMTCQhBCCmSAHHJgKayCQiiGzbAdKmAv1EAdNMBRaIaTcA4uwlW4Dj1wD/phCJ7BKLyBCQRByAgTYSHaiAFiilgjjggXmYX4IcFIBBKLJCDJiBRRIkuRNUgxUopUIFVIHfI9cgI5h1xGupE7yAAygvyGvEcxlIGyUT3UDLVDuag3GoRGogvQZHQxmo8WoJvQcrQaPYw2oefQq2gP2o8+Q8cwwOgYBzPEbDAuxsNCsTgsCZNjy7EirAyrxhqwVqwDu4n1Y8+xdwQSgUXACTYEd0IgYR5BSFhMWE7YSKggHCQ0EdoJNwkDhFHCJyKTqEu0JroR+cQYYjIxh1hILCPWEo8TLxB7iEPENyQSiUMyJ7mQAkmxpFTSEtJG0m5SI+ksqZs0SBojk8naZGuyBzmULCAryIXkneTD5DPkG+Qh8lsKnWJAcaT4U+IoUspqShnlEOU05QZlmDJBVaOaUt2ooVQRNY9aQq2htlKvUYeoEzR1mjnNgxZJS6WtopXTGmgXaPdpr+h0uhHdlR5Ol9BX0svpR+iX6AP0dwwNhhWDx4hnKBmbGAcYZxl3GK+YTKYZ04sZx1QwNzHrmOeZD5lvVVgqtip8FZHKCpVKlSaVGyovVKmqpqreqgtV81XLVI+pXlN9rkZVM1PjqQnUlqtVqp1Q61MbU2epO6iHqmeob1Q/pH5Z/YkGWcNMw09DpFGgsV/jvMYgC2MZs3gsIWsNq4Z1gTXEJrHN2Xx2KruY/R27iz2qqaE5QzNKM1ezUvOUZj8H45hx+Jx0TgnnKKeX836K3hTvKeIpG6Y0TLkxZVxrqpaXllirSKtRq0frvTau7aedpr1Fu1n7gQ5Bx0onXCdHZ4/OBZ3nU9lT3acKpxZNPTr1ri6qa6UbobtEd79up+6Ynr5egJ5Mb6feeb3n+hx9L/1U/W36p/VHDFgGswwkBtsMzhg8xTVxbzwdL8fb8VFDXcNAQ6VhlWGX4YSRudE8o9VGjUYPjGnGXOMk423GbcajJgYmISZLTepN7ppSTbmmKaY7TDtMx83MzaLN1pk1mz0x1zLnm+eb15vft2BaeFostqi2uGVJsuRaplnutrxuhVo5WaVYVVpds0atna0l1rutu6cRp7lOk06rntZnw7Dxtsm2qbcZsOXYBtuutm22fWFnYhdnt8Wuw+6TvZN9un2N/T0HDYfZDqsdWh1+c7RyFDpWOt6azpzuP33F9JbpL2dYzxDP2DPjthPLKcRpnVOb00dnF2e5c4PziIuJS4LLLpc+Lpsbxt3IveRKdPVxXeF60vWdm7Obwu2o26/uNu5p7ofcn8w0nymeWTNz0MPIQ+BR5dE/C5+VMGvfrH5PQ0+BZ7XnIy9jL5FXrdewt6V3qvdh7xc+9j5yn+M+4zw33jLeWV/MN8C3yLfLT8Nvnl+F30N/I/9k/3r/0QCngCUBZwOJgUGBWwL7+Hp8Ib+OPzrbZfay2e1BjKC5QRVBj4KtguXBrSFoyOyQrSH355jOkc5pDoVQfujW0Adh5mGLw34MJ4WHhVeGP45wiFga0TGXNXfR3ENz30T6RJZE3ptnMU85ry1KNSo+qi5qPNo3ujS6P8YuZlnM1VidWElsSxw5LiquNm5svt/87fOH4p3iC+N7F5gvyF1weaHOwvSFpxapLhIsOpZATIhOOJTwQRAqqBaMJfITdyWOCnnCHcJnIi/RNtGI2ENcKh5O8kgqTXqS7JG8NXkkxTOlLOW5hCepkLxMDUzdmzqeFpp2IG0yPTq9MYOSkZBxQqohTZO2Z+pn5mZ2y6xlhbL+xW6Lty8elQfJa7OQrAVZLQq2QqboVFoo1yoHsmdlV2a/zYnKOZarnivN7cyzytuQN5zvn//tEsIS4ZK2pYZLVy0dWOa9rGo5sjxxedsK4xUFK4ZWBqw8uIq2Km3VT6vtV5eufr0mek1rgV7ByoLBtQFr6wtVCuWFfevc1+1dT1gvWd+1YfqGnRs+FYmKrhTbF5cVf9go3HjlG4dvyr+Z3JS0qavEuWTPZtJm6ebeLZ5bDpaql+aXDm4N2dq0Dd9WtO319kXbL5fNKNu7g7ZDuaO/PLi8ZafJzs07P1SkVPRU+lQ27tLdtWHX+G7R7ht7vPY07NXbW7z3/T7JvttVAVVN1WbVZftJ+7P3P66Jqun4lvttXa1ObXHtxwPSA/0HIw6217nU1R3SPVRSj9Yr60cOxx++/p3vdy0NNg1VjZzG4iNwRHnk6fcJ3/ceDTradox7rOEH0x92HWcdL2pCmvKaRptTmvtbYlu6T8w+0dbq3nr8R9sfD5w0PFl5SvNUyWna6YLTk2fyz4ydlZ19fi753GDborZ752PO32oPb++6EHTh0kX/i+c7vDvOXPK4dPKy2+UTV7hXmq86X23qdOo8/pPTT8e7nLuarrlca7nuer21e2b36RueN87d9L158Rb/1tWeOT3dvfN6b/fF9/XfFt1+cif9zsu72Xcn7q28T7xf9EDtQdlD3YfVP1v+3Njv3H9qwHeg89HcR/cGhYPP/pH1jw9DBY+Zj8uGDYbrnjg+OTniP3L96fynQ89kzyaeF/6i/suuFxYvfvjV69fO0ZjRoZfyl5O/bXyl/erA6xmv28bCxh6+yXgzMV70VvvtwXfcdx3vo98PT+R8IH8o/2j5sfVT0Kf7kxmTk/8EA5jz/GMzLdsAAAAgY0hSTQAAeiUAAICDAAD5/wAAgOkAAHUwAADqYAAAOpgAABdvkl/FRgAAFXhJREFUeNrs3Xm4FNWZx/EfXAEFFRQ0SnDfgiyiqOO+xH3XYMQYg0ZUXCMRYySuMEYdjZhJ3CdkNHFcIoJLUGMSB7cxbolRVByUEAmyiqAoS4Azf5y3pw91q7tPd1ff7nv5fp6nHi7dtVd1nfes1c45JwAAsGZpzykAAIAAAAAAEAAAAAACAAAAQAAAAAAIAAAAAAEAAAAgAAAAAAQAAACAAAAAABAAAAAAAgAAAEAAAAAACAAAAAABAAAAIAAAAAAEAAAAgAAAAAACAAAAQAAAAAAIAAAAAAEAAAAgAAAAAAQAAACAAAAAABAAAAAAAgAAAEAAAAAACAAAAAABAAAAIAAAAAAEAAAAgAAAAAAQAAAAAAIAAAAIAAAAAAEAAAAgAAAAAAQAAACAAAAAABAAAAAAAgAAAEAAAAAA6m0tTkHD+oqkEyTtJ6mvpF52vVY1cDA5T9KLkp6RNF7Skhba9maSHpC0o6SVNTq2tySdJukjbs2aGy5phCQn6QZJtzfY/o2wfXSSxkj6aSs8x10kHWK/lydr9LtBg2vnnOMsNJ6Rkq6UtE4rPoZZki6T9KsW2NZFLfQQvkjSz7g9a2ovSS8lPustaUqD7N+RkiYmPjtY0h9b0TkeIOlpy2RI0lRJh0qazu1HCQDqZ237Ye7fBo5lU0n3StpN0oU13tby4O+FVhKR9b09WdJD3KI1d2PKZ6MkDW6Q/ds95bNdWlEA0CGR+EvSdpIek7QTtx8BAOrnJXuYtCUX2HE9WMNthMWXt8qXnqD16Slp75TPT5J0nqRPGmAfl0R+1qj2TCT+Of3t/H/MbbjmoBFg47ivDSb+OTe34LaWcyu1WpcW+e7MBtnHtDY4rakedW6R777kFiQAQMvbQ9K323jO7qgW2lYnbqdWqZOk84t8fx6nKBNT5Kvmkv5NvvoMBABoYXetAcd4PpcZRZyi4lWSm0s6jtOUidMlXS/fruUtSZfLN9jFGoY2APXX36a27nD5rkdfcMmR4tLIeR7jVGXiRzaBAAB1dHQZ8/5Z0p/k67nbZbgP7eTrNp1Ni+Ub720YsexnlrA3RWzjdEm3ccmRsJ+kryU+e9qCxUHBZ3tJ2kLS3zllAAFAWxDb8G+UpGtacL9GRCb+m0s6WdKdEfOfRQCAFMNTPhst6cNEACBJV0kayikDCADagh0i5nmthRP/Gy1XX8oDkhZJGhcZAOwk6auSZrbh67mB/BgIXe3/i+x4F9VgW02StpQvqeko3x1ttuK7ctWqSqaz4luUbyI/4mVouaSX7e+FkroF3w2RdK6y7e3RRdLG8n3kv5Q0R9I/a3yfNFnw3M2OZbbK6+bY1c5dZ7vus2p0j8VY3/ali6Rl8uNwzOPR3vhoBFh/m0bM09ID0AyKnG+8/fuJpFcilxncBq/h9vJD1r4qP1TwO5L+x6Z3JM2wBG20JdjVOkHSBNvWB7bdFyW9YZ/9r6Sx8r1LCgX+99t+fS/jc/Gy7cOpkfNfkvLZL4K/f5qy79/NYD+3lnSt7e8MSdMkvS9fvfB3+eGsz48MhJM6SvqlpPckPSs/RHXOQZIetm1Mk6/Wm2zn7BX5dg6FerJ0l3RFcI6n2PLv2f+fV3xvicts+x8WWWao3UvT7d4Nqx17WqYkty/v277k7vd37DruxSO+gTnnmOo7LXKlndmC+9PfxfnCObdWsNwZkctNqcE+nx2s/9oWPFfbOOfuc+VZ5Zwb65zbrILt9XPOPV/m9sY55zZJrGed4PsVGZ6PYxPbjVlmQco+9w6+75Hy/Ywq9nFD59zddh1izHHOjQyWvzxlnvMT27gr8f3rzrmtnHMPRW7zI+fcNxLr/FHks8I55yY75/aIvE45eyXm2T1lnp3tu5udc8vKuAefdM7txLO+8SaqAOrvcytCK1V03lLOjpzvQUkrgv9PsFxnTJXHDpZjaM1OtePtGHz2qXwjzSmS5ttnG8mPZb+HFdu2k3SGlYQMCUpRSulrOazwN/u65fr/Ydeim6RtLde1aVCas7/lPN+yz5ZYtc2JVhQ9XNm8S+Ha4O/rIuY/xapMQm9YjjZnvvwwuwcFn/WSdICkSWXu3x6SHlX6SHiFbGzHcpht862IZfZJ/H+A5fI7R25zM0mPyL934ClJT6i8xsJ9LGe+t5VCJe1Z4LNw3t1S5hluJSKDyjzvR9g0WNJveORTAsCUnyZFRNCLnXM9W2h/ZkVG9fukLPtC5LI/bOUlAMlc4Gzn3FnOua5Flulm+zknsewFEdtr75ybHyzzlxI5vE7OudMSuesvnXPbBvNsF3y3IINzclCwvmcjl3kv5d44JmW+AwrkKsvZv31d9Z62+6tUCcDLLhvLnXNvVrH8CufcRinn4sqUeYcl5hnqauMYnvmUACBvskq//KeL5fautNzlClXeDbBdgWVXWc5hk4h1LFTzN7bJcsT7RCz/HfmRx2qh1sOZDk3kdH8p/5bAxRHn7G4rOfl3+S6RkvRz+QZcjxRZ9mSr/5V8g9DdS2xrmfxob0/Jv+p1oPybJR+WtLPNM9W+P8Jy4d+07yt1VfB3TA+Svmre9W+R5XaTJlk98+aJXOU2Vocdk6N+tsB3i+WH4Z5kdeLLrKSmj+XAjwnmPcymUkq9svtOSX+wkptOkvpJ+paavwehQ0rp31L59108J9/Qbl1Ju8oPlbxtYt4m+WG4h0TsnyvzGGTtJJ6W9K6kBfIvM9vCShNOVno34sftXl7Ao58SACbnTnKtz71Fcp7LI9fRt0YlADdbTnzDCqe1i2xn88Qx3FTFPo9JrGvTIvM+Hsy3S5nb6WB1wsudc9ckvtszWO+0Ko5lQLCetyOXSasPv6HI/Gm51jGR2yqUI78/pX1EcjrQ2q0UkywBeKnAfPOtbj32nkj6wDm3ZYFlm5xzEwsst1GJEixnv6Fwnu8W2Y+ZzrkjS5y3DZxz9xRYfjzP/caYOAn1n9ZrhQHAfkWO58nIdVxRowBguXPuc2ukWO70pXNurnNuUER1zaMZ7PfvItf3blCM377CbRUKMF4P9uGACtf922Adh0fM373APdGjyDK9Uub/NOJ8HFtgW6PKOL6mxHmqNAAYELGt54s0ut0wYvkZEftXTQAwzxL32HN3S4H1bMmzv/4T3QAboxHgHa1of+fJdzcqJLbL4gk12r8OVizauYJpHWu0d1GBRlK5qprl8q+ordZxQUPK46zYOU3ud7qWFbNWYlaBz68I/v5xBesNX/Q0zYqES0l7s9/vgoaTaf6h5sMAd1PptwSOSvnsXklXl3GMK61hZTXF1ndLejNivkKNJ2+K3P71KZ/tnOHv62hr7Brr+1bNmdQWuwO3OgQAjeFiSX9rJfv6RInvf6O4wWV2SamzzMJ8q5OcUsH0vrW1SEsczkokKlkMRLNUq7e+L/TCpD8Fwc2wjM/X05a4yhK53cpc/oYSiW1SO0sUkn4SsewtKZ8NL1H3PyClzr+ScQSWV3nu74uc742U+nen9Df4FbtXQr0yuleeU/x4H6G09j77CAQA+P+EYG4r2dcHSny/RNLEyHXV4hXIt1lOuncF09csAfzvlPUeHDyMsxzO+Obg769HPEDH1CD3NLJAiUAp68k36JT86IO/ilhmkJp3w5sq3yguJgFKlmT0LhK0nJjy2Y1q3uAt1jj5gXEq8VHkfAvUfETA2WVkENJy5+tmdJ+8WOFyj9ozLrStQAAASb5P+b+0gv2cFfmgHhe5vmNqsI+rarDO7Sw3Kfli3CyHXJ2tfL/37SX1SJnnPa3+utYH7ToMVXl92ovlTj+3v4+VHyUvxuXB3zdFLpNWvVJOFVjadgqVPKT9ph6u8lyNr3C5lWXcv0tTgupqnulZPedXVLjcYgvyQhvx2CcAQPNcYCObEDnfRMV1xxuYUQIW6liD4+4b/D25But/x/5tJ2mrIqUAI4KE5CD5oVanyw/gMlb+9a6DLJAoV1h3PDpi/s7KD+P7haS7Ipbpo+ZFvysl3VPGfqYNNnWE8t0kQ8kurYsU122wmLcrXK4pcr72Kc/lpjK2k9bF12V0n1bTbTwZNK8tEABA+8uPNtYaPBI535eKbww4pBUcdzhSYy36L4frLFZcO0Z+FMVfBwHW2vINFM+Qb8Q3Tr4tw2QLCGLrf2+U7wMv+aqZ9UrMPyxImG6MzKVeVuCzchqVfVagFCCtZCF5Lmer+pf8LIhMdFH8HDlOSf0xEFD9HVrGvP8pP6BMVoHbKvnBVWKG9pyv9LrxQsYprrHVSYovPm7EB1n [...]

2024-01-30 10:17 UTC, Blumlaut commented on language/en.json
> +    "bansuffix": ", Banned by: ",
Hm, no better way to achieve this? :/

What about the regex i gave you? or does that not work with Lua's regex implementation?

2024-01-31 00:31 UTC, Gravxd commented on language/en.json
> +    "bansuffix": ", Banned by: ",
Didn't get a chance to test was on a laptop whilst setting up a new computer - i'll put this on list to test when free as this will be final part of code changes before we can make this release ready 👍🏻

2024-02-10 20:08 UTC, Gravxd commented
Apologies for delay - practically had to overhaul entire setup with new computer//internet and had to wait to get back a lot of files etc - changes have been corrected using regex to be compatible with all languages - thanks for your patience

2024-03-05 02:24 UTC, Gravxd commented
Any chance of this being merged or should we close out?

2024-03-05 05:59 UTC, Blumlaut commented
haven't been near a fivem compatible computer for a while, can I merge this blindly? if so I might just do that..

2024-03-07 10:33 UTC, Blumlaut requested changes
looks good apart from that function that seemingly never gets referenced, i'll merge it  once thats addressed

2024-03-07 10:33 UTC, Blumlaut commented on shared/util_shared.lua
> +function getRawBanReason(inputStr, suffix)
only thing i see here is that getRawBanReason is not currently referenced anywhere, can this be removed?

2024-03-11 11:38 UTC, Gravxd commented on shared/util_shared.lua
> +function getRawBanReason(inputStr, suffix)
No problem - old function , has been removed

2024-03-11 11:39 UTC, Gravxd commented
Unused function removed - should be all good

2024-03-11 12:26 UTC, Blumlaut commented
perfect! merging this then.

2024-03-11 12:26 UTC, merged